import mongoose from "mongoose";

const admissionSchema = new mongoose.Schema({
  // Unique Application ID (Generated by Server)
  applicationId: { type: String, required: true, unique: true },

  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  // New Parent Fields
  fatherName: { type: String, required: true },
  motherName: { type: String, required: true },
  
  email: { type: String, required: true },
  phone: { type: String, required: true },
  dob: { type: Date, required: true },
  gender: { type: String, required: true },
  address: { type: String, required: true },
  
  // Academic - SSLC (10th)
  sslcSchool: { type: String, required: true },
  sslcPercentage: { type: String, required: true },
  sslcYear: { type: String, required: true },

  // Academic - PUC (12th)
  pucCollege: { type: String, required: true },
  pucPercentage: { type: String, required: true },
  pucYear: { type: String, required: true },
  
  // Program
  department: { type: String, required: true },
  program: { type: String, required: true },
  
  // Files
  photo: { type: String, required: true },
  transcript: { type: String, required: true },

  status:{type: String, required:true, default: "Pending"}
}, { timestamps: true });

const AdmissionModel = mongoose.models.Admission || mongoose.model("Admission", admissionSchema);

export default AdmissionModel;